on: [push]
name: Run Test

jobs:
  loc-count:
    runs-on: ubuntu-latest
    name: LoC
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Main-Build
        uses: addnab/docker-run-action@v2
        with:
          image: tsukisuperior/tsos-build:latest
          options: -v ${{ github.workspace }}:/
          run: |
            /build.sh pc
