name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-pc:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v2
        with:
          image: tsukisuperior/tsos-build:latest
          run: |
            "./build.sh pc"

  build-test-gba:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v2
        with:
          image: tsukisuperior/tsos-build:latest
          run: |
            "./build.sh gba"
