on:
  push:
    branches: [master]
    tags:
      - "v*"

name: CANON-A1100 Compile test

jobs:
  canon-a1100-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && python3 ./build.py canon-a1100
