on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CANON-A1100 Compile test

jobs:
  gba-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && python3 ./build.py canon-a1100

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CANON A1100 Nucleus
          path: build/nucleus
