on: [push]
name: Compile test

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:  
    - uses: actions/checkout@v2
    - name: Look at /usr
      run: ls -la /usr
