on: [push]
name: Compile test

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:  
    - uses: actions/checkout@v2
    - name: Look at /usr
      run: cd ~/Documents && git clone https://github.com/tsuki-superior/tsos-nucleus && cd tsos-nucleus && ./build.sh pc
