on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: NSPIRE CX Compile test

jobs:
  nspire-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && python3 ./build.py nspire

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NSPIRE Nucleus
          path: |
            build/nucleus
            build/nucleus.elf
          if-no-files-found: error
