on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: NSPIRE Compile test

jobs:
  nspire-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && python3 ./build.py nspire
