on: [push]

name: Compile test

jobs:
  pc-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && ./build.sh pc

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: build/nucleus
  gba-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && ./build.sh gba
  psx-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && ./build.sh psx
  nspire-test:
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/tsos-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Test
        run: PATH=$PATH:/usr/tsos-toolchain/bin && cd $GITHUB_WORKSPACE && ./build.sh nspire
