on: [push]
name: Run Test

jobs:
  line_count:
    runs-on: ubuntu-latest
    name: Test Run
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Launch the local action
        uses: ./ # Uses an action in the root directory
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/badge.svg
